name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Install .NET 7.0 SDK
      - name: Set up .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.0
      
      # Continue with other steps (like installing retype, building docs, etc.)
      - name: Install Retype
        run: dotnet tool install --global retype --version 3.6.0

      - uses: retypeapp/action-build@latest
      #   with:
      #     license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
